image: node:7.10.0

cache:
  paths:
  - node_modules/

compile source:
  script:
   - npm install
   - npm install -g typescript
   - tsc -p tsconfig.json
 
test_binningcompression:
   script:
    - node ./dist/test/BinningCompression.spect.js

 
